# Exported from Render on 2024-07-14T04:06:42Z
services:
- type: web
  name: capstr-web
  runtime: node
  repo: https://github.com/therealjimjelly/capstr-web-server
  plan: free
  envVars:
  - key: SECRET_KEY
    sync: false
  region: virginia
  buildCommand: npm install
  startCommand: node server.js
version: "1"
