  
  #################################################################
# Example render.yaml                                           #
# Do not use this file directly! Consult it for reference only. #
#################################################################

# List all services *except* PostgreSQL databases here
services:

  - type: web
    runtime: node
    name: capstr-web
    repo: https://github.com/render-examples/sinatra # Default: Repo containing render.yaml
    numInstances: 1   # Manual scaling configuration. Default: 1 for new services
    region: oregon # Default: oregon
    plan: free    # Default: starter
    branch: main      # Default: master
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: false # Disable automatic deploys
    maxShutdownDelaySeconds: 120 # Increase graceful shutdown period. Default: 30, Max: 300
    envVars: # Environment variables
        - key: SECRET_KEY
          sync: false